# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  deploymentQueuing.enable: true

stages:
- stage: build
  jobs:
  - job:
    steps:
    - script: echo 'hello world'

- stage: deploy_dev
  jobs:  
  - deployment: deploy1
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
            - powershell: |
                Write-Output "Environment.Id: " $(Environment.Id)
            - powershell: Write-Output "Hello World"
              condition: not(eq(variables['environment.id'],''))

- stage: deploy_test
  jobs:  
  - deployment: deploy2
    environment: TEST
    strategy:
      runOnce:
        deploy:
          steps:
            - powershell: |
                Write-Output "Environment.Id: " $(Environment.Id)
            - powershell: Write-Output "Hello World"
              condition: not(eq(variables['environment.id'],''))
