###############################################################################
# Marketplace Extension 
#
# Packages and publishes the deploymentqueuing-extension to the marketplace
###############################################################################
trigger: 
  paths:
    include:
    - src
    - devops/pipelines/marketplace-extension/pipeline.yml
  
pool:
  vmImage: "ubuntu-latest"

variables:
- group: pipeline-extension-settings

stages:
  - stage: build_package
    displayName: Build and Publish
    jobs:
      - job: build
        steps:
          # install the extension cli tool
          - task: TfxInstaller@3
            displayName: Use Tfx
            inputs:
              version: "v0.7.x"

          # fetch the current extension version
          #   You must build and upload manually for the first execution
          - task: QueryAzureDevOpsExtensionVersion@3
            displayName: Fetch Current Extension Version
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'AzureDevOpsMarketplace'
              publisherId: '$(PublisherID)'
              extensionId: '$(ExtensionID)'
              versionAction: 'Patch'
              outputVariable: 'Task.Extension.Version'
          
          # Create the vsix package
          - task: PackageAzureDevOpsExtension@3
            displayName: Package Extension
            inputs:
              rootFolder: '$(System.DefaultWorkingDirectory)/src'
              publisherId: '$(PublisherID)'
              extensionId: '$(ExtensionID)'
              extensionName: '$(ExtensionName)'
              extensionVersion: '$(Task.Extension.Version)'
              updateTasksVersion: true
              updateTasksVersionType: 'patch'
              extensionVisibility: 'private' 
              extensionPricing: 'free'

          # Upload and publish the extension
          - task: PublishAzureDevOpsExtension@3
            displayName: Publish Extension
            condition: eq(variables['Source.BranchName'], 'refs/heads/main')
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'AzureDevOpsMarketplace' 
              fileType: 'vsix'
              vsixFile: '$(System.DefaultWorkingDirectory)/*.vsix'
              publisherId: '$(PublisherID)'
              extensionId: '$(ExtensionID)'
              extensionName: '$(ExtensionName)'
              updateTasksVersion: false
              extensionVisibility: 'private' # Pipeline Decorators must be private
              extensionPricing: 'free'
              shareWith: $(SharedWith)